// CONFIG
export const CHANGE_URL = 'CHANGE_URL';
export const CONNECTING_WS = 'CONNECTING_WS';
export const TOGGLE_APP_STATE = 'TOGGLE_APP_STATE';

// COLORS
export const ALL_LEAGUES_TOKEN_COLOR = '#A24876';